# Generated by Django 4.2.26 on 2025-11-11 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Produk')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi Detail')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga (Rp)')),
                ('category', models.CharField(choices=[('Pashmina', 'Pashmina'), ('Jilbab Segi Empat', 'Jilbab Segi Empat')], max_length=50, verbose_name='Kategori')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Gambar')),
                ('is_new_arrival', models.BooleanField(default=False, verbose_name='Produk Baru?')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tag (Contoh: Sale, Best Seller)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Judul Promo')),
                ('tagline', models.CharField(max_length=255, verbose_name='Tagline Kecil')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi Singkat Promo')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Mulai Promo')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Berakhir Promo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif (Tampilkan di website)')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promosi',
                'ordering': ['-start_date'],
            },
        ),
    ]
